In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [5]:
df =  pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    500     80   John
1  2023-01-02       B   West    414     31   Mary
2  2023-01-03       C  North    927     60    Bob
3  2023-01-04       D  South    697     17  Alice
4  2023-01-05       A   East    858     87   John
5  2023-01-06       B   West    379     78   Mary
6  2023-01-07       C  North    386     68    Bob
7  2023-01-08       D  South    880     91  Alice
8  2023-01-09       A   East    579     26   John
9  2023-01-10       B   West    116     85   Mary
10 2023-01-11       C  North    816     28    Bob
11 2023-01-12       D  South    678     33  Alice
12 2023-01-13       A   East    475     30   John
13 2023-01-14       B   West    758     23   Mary
14 2023-01-15       C  North    482     30    Bob
15 2023-01-16       D  South    406     51  Alice
16 2023-01-17       A   East    163     31   John
17 2023-01-18       B   West    616     73   Mary
18 2023-01-19       C  North    386     81    Bob
19 2023-01-20       D  South    201     75  Alice

In [7]:
pd.pivot_table(df,values= 'Sales',index= 'Region',columns='Product',aggfunc = 'median')

Product      A      B      C      D
Region
East     500.0    NaN    NaN    NaN
North      NaN    NaN  482.0    NaN
South      NaN    NaN    NaN  678.0
West       NaN  414.0    NaN    NaN

In [9]:
ptv2 = pd.pivot_table(df,values= ['Sales','Units'],index= 'Region',columns='Product')
ptv2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     515.0    NaN    NaN    NaN  50.8   NaN   NaN   NaN
North      NaN    NaN  599.4    NaN   NaN   NaN  53.4   NaN
South      NaN    NaN    NaN  572.4   NaN   NaN   NaN  53.4
West       NaN  456.6    NaN    NaN   NaN  58.0   NaN   NaN

## Cross Tabs

In [11]:
pd.crosstab(df['Region'],df['Product']) ## used for count

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0